# Generated by Import Script

resource "github_actions_secret" "netlify_auth_token" {
  repository  = "public-smart-food-logger"
  secret_name = "NETLIFY_AUTH_TOKEN"
  # values are sensitive and cannot be imported directly.
  # You need to set 'plaintext_value' or 'encrypted_value' in the next apply to manage it.
  # For now, we use a placeholder or ignore changes to import existence.
  # plaintext_value = "TODO_SET_VALUE"

  lifecycle {
    ignore_changes = [plaintext_value, encrypted_value]
  }
}



resource "github_actions_secret" "netlify_site_id" {
  repository  = "public-smart-food-logger"
  secret_name = "NETLIFY_SITE_ID"
  # values are sensitive and cannot be imported directly.
  # You need to set 'plaintext_value' or 'encrypted_value' in the next apply to manage it.
  # For now, we use a placeholder or ignore changes to import existence.
  # plaintext_value = "TODO_SET_VALUE"

  lifecycle {
    ignore_changes = [plaintext_value, encrypted_value]
  }
}




